/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tog_framework_steam_SteamProxy */

#ifndef _Included_com_tog_framework_steam_SteamProxy
#define _Included_com_tog_framework_steam_SteamProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tog_framework_steam_SteamProxy
 * Method:    _initSteamAPI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tog_framework_steam_SteamProxy__1initSteamAPI
  (JNIEnv *, jobject);

/*
 * Class:     com_tog_framework_steam_SteamProxy
 * Method:    _closeSteamAPI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_tog_framework_steam_SteamProxy__1closeSteamAPI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
